const getNodes = () => [
  /* ───────────── DOCUMENTE / INPUT EXTERNE  ───────────── */
  {
    id: 'd1',
    position: { x: 20, y: 55 },
    label: 'temă+documente analiză teren',
    className: 'proiectare-flow extern w-[160px]',
    showIndex: true,
  },
  {
    id: 'd2',
    position: { x: 20, y: 135 },
    label: 'documente teren pentru CU',
    showIndex: true,
    className: 'proiectare-flow extern w-[160px]',
  },
  {
    id: 'd3',
    position: { x: 20, y: 215 },
    label: 'temă proiectare concept',
    className: 'proiectare-flow extern w-[160px]',
    showIndex: true,
  },
  {
    id: 'd4',
    position: { x: 7, y: 295 },
    label: 'temă soluții tehnice',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd5',
    position: { x: 20, y: 355 },
    label: 'listă cerințe preliminare NZEB',
    className: 'proiectare-flow extern w-[160px]',
    showIndex: true,
  },
  {
    id: 'd6',
    position: { x: 1, y: 435 },
    label: 'decizie fazare proiect',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd7',
    position: { x: 2, y: 575 },
    label: 'feedback dezvoltare și vânzări',
    className: 'proiectare-flow extern w-[194px]',
    showIndex: true,
  },
  {
    id: 'd8',
    position: { x: 9, y: 749 },
    label: 'concept spații verzi',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd9',
    position: { x: 25, y: 810 },
    label: 'concept sistematizare',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd10',
    position: { x: 40.2, y: 930 },
    label: 'raport NZEB',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd11',
    position: { x: 25, y: 1049 },
    label: 'decizii aspecte interpretabile',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd12',
    position: { x: 35, y: 1129 },
    label: 'aviz Apa Nova',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd13',
    position: { x: 13, y: 1431 },
    label: 'proiect spații verzi',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd14',
    position: { x: 24.5, y: 1491 },
    label: 'proiect sistematizare',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd15',
    position: { x: 15, y: 1736 },
    label: 'temă materiale + soluții supra',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd16',
    position: { x: 15, y: 1820 },
    label: 'temă finisaje arhitecturale',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd17',
    position: { x: 24, y: 2011 },
    label: 'validare echipamente',
    className: 'proiectare-flow extern w-[150px]',
    showIndex: true,
  },
  {
    id: 'd18',
    position: { x: 15, y: 2195 },
    label: 'feedback execuție',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd19',
    position: { x: 1245, y: 356 },
    label: 'studiu geotehnic',
    className: 'proiectare-flow extern w-[191px]',
    showIndex: true,
  },
  {
    id: 'd20',
    position: { x: 1245, y: 416 },
    label: 'ridicare topografică',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd21',
    position: { x: 1245, y: 476 },
    label: 'studiu hidrologic',
    className: 'proiectare-flow extern w-[191px]',
    showIndex: true,
  },
  {
    id: 'd22',
    position: { x: 1255, y: 565 },
    label: 'temă soluții arhitecturale + echipamente',
    className: 'proiectare-flow extern w-[170px]',
    showIndex: true,
  },
  {
    id: 'd23',
    position: { x: 1252, y: 725 },
    label: 'poziții + înălțimi macarale',
    className: 'proiectare-flow extern w-[175px]',
    showIndex: true,
  },
  {
    id: 'd24',
    position: { x: 1252, y: 900 },
    label: 'studii consultanți avizare',
    className: 'proiectare-flow extern w-[175px]',
    showIndex: true,
  },
  {
    id: 'd25',
    position: { x: 1265, y: 1249 },
    label: 'temă cerințe OS',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd26',
    position: { x: 1254, y: 1340 },
    label: 'poziții + proiect fundații macarale',
    className: 'proiectare-flow extern w-[170px]',
    showIndex: true,
  },
  {
    id: 'd27',
    position: { x: 1254, y: 1634 },
    label: 'temă uși tehnice + ALA în infra',
    className: 'proiectare-flow extern w-[170px]',
    showIndex: true,
  },
  {
    id: 'd28',
    position: { x: 1254, y: 1736 },
    label: 'detalii tehnice piese înglobate',
    className: 'proiectare-flow extern w-[170px]',
    showIndex: true,
  },
  {
    id: 'd29',
    position: { x: 1260, y: 2017 },
    label: 'structură buget',
    className: 'proiectare-flow extern',
    showIndex: true,
  },
  {
    id: 'd30',
    position: { x: 1255, y: 2157 },
    label: 'feedback execuție',
    className: 'proiectare-flow extern',
    showIndex: true,
  },

  /* ───────────── INSTALAȚII  ───────────── */
  {
    id: 'i1',
    position: { x: 257, y: 106 },
    label: 'analiză instalații teren',
    className: 'proiectare-flow green w-[190px]',
    showIndex: true,
  },
  {
    id: 'i2',
    position: { x: 215, y: 336 },
    label: 'temă spații tehnice + conformare',
    className: 'proiectare-flow green w-[295px]',
    showIndex: true,
  },
  {
    id: 'i3',
    position: { x: 253, y: 517 },
    label: 'concept instalații spații comune + echipamente',
    className: 'proiectare-flow green w-[220px]',
    showIndex: true,
  },
  {
    id: 'i4',
    position: { x: 224, y: 667 },
    label: 'concept instalații apartamente',
    className: 'proiectare-flow green',
    showIndex: true,
  },
  {
    id: 'i5',
    position: { x: 256.5, y: 780 },
    label: 'temă auditor energetic',
    className: 'proiectare-flow green',
    showIndex: true,
  },
  {
    id: 'i6',
    position: { x: 238.5, y: 976 },
    label: 'date pentru memorii tehnice',
    className: 'proiectare-flow green',
    showIndex: true,
  },
  {
    id: 'i7',
    position: { x: 245.5, y: 1270 },
    label: 'planuri nivel SI și PC',
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i8',
    position: { x: 245.5, y: 1330 },
    label: 'planuri instalații fundații',
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i9',
    position: { x: 245.5, y: 1390 },
    label: 'documentație DTAC',
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i10',
    position: { x: 290, y: 1600 },
    label: 'planuri instalații infra',
    className: 'proiectare-flow green w-36',
  },
  {
    id: 'i11',
    position: { x: 255, y: 1797 },
    label: 'planuri supra + calcule',
    className: 'proiectare-flow green',
  },
  {
    id: 'i12',
    position: { x: 252, y: 1868.8 },
    label: 'PT infra (planuri + cantități + piese scrise)',
    className: 'proiectare-flow green w-[220px]',
  },
  {
    id: 'i13',
    position: { x: 252, y: 1960 },
    label: 'PT supra (planuri + cantități + piese scrise)',
    className: 'proiectare-flow green w-[220px]',
  },
  {
    id: 'i14',
    position: { x: 224.5, y: 2040 },
    label: 'temă finală planuri goliri infra',
    className: 'proiectare-flow green',
  },
  {
    id: 'i15',
    position: { x: 272, y: 2100 },
    label: 'planuri elemente înglobate în beton',
    className: 'proiectare-flow green w-[180px]',
  },
  {
    id: 'i16',
    position: { x: 257, y: 2277 },
    label: 'PT actualizat cu echipamente selectate',
    className: 'proiectare-flow green w-[210px]',
  },
  {
    id: 'i17',
    position: { x: 257, y: 2357 },
    label: 'fișe tehnice apartamente',
    className: 'proiectare-flow green w-[229px]',
  },
  {
    id: 'i18',
    position: { x: 257, y: 2417 },
    label: 'documentație AS-BUILT',
    className: 'proiectare-flow green w-[229px]',
  },
  {
    id: 'i19',
    position: { x: 257, y: 2477 },
    label: 'documentație ASI',
    className: 'proiectare-flow green w-[229px]',
  },

  /* ───────────── ARHITECTURĂ  ───────────── */
  {
    id: 'a1',
    position: { x: 653.4, y: 106 },
    label: 'analiză teren',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a2',
    position: { x: 559.8, y: 186 },
    label: 'documentație certificat de urbanism',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a3',
    position: { x: 630.4, y: 295 },
    label: 'concept preliminar',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a4',
    position: { x: 595.5, y: 476 },
    label: 'concept detaliat preliminar',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a5',
    position: { x: 617.4, y: 626 },
    label: 'concept final detaliat',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a6',
    position: { x: 602, y: 708 },
    label: 'concept validat',
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a7',
    position: { x: 614, y: 847 },
    label: 'temă auditor energetic',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a8',
    position: { x: 600, y: 930 },
    label: 'documentații avize simple',
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a9',
    position: { x: 602, y: 1007 },
    label: 'documentații avize: DSP, Mediu etc.',
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a10',
    position: { x: 602, y: 1100 },
    label: 'documentații avize SI & PC',
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a11',
    position: { x: 601.9, y: 1180 },
    label: 'documentație circulație',
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a12',
    position: { x: 604.5, y: 1290 },
    label: 'documentație DTAC + DTOE',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a12.1',
    position: { x: 530, y: 1382 },
    label: 'concept fațadă revizuit',
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.2',
    position: { x: 530, y: 1442 },
    label: 'planuri nivel preliminare',
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.3',
    position: { x: 530, y: 1502 },
    label: 'planuri nivel finale',
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.4',
    position: { x: 530, y: 1562 },
    label: 'documentație DTAC actualizată',
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a13',
    position: { x: 650, y: 1654 },
    label: 'fișă de proiect',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a14',
    position: { x: 530, y: 2015 },
    label: 'detalii fațadă finale',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a14.1',
    position: { x: 526, y: 1736 },
    label: 'temă arhitectură PT ➜ instalații',
    className: 'proiectare-flow primary w-[188px]',
  },
  {
    id: 'a14.2',
    position: { x: 724, y: 1736 },
    label: 'temă arhitectură PT ➜ structură',
    className: 'proiectare-flow primary w-[188px]',
  },
  {
    id: 'a15',
    position: { x: 613, y: 1838 },
    label: 'planuri coordonatoare',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a16',
    position: { x: 585, y: 1918 },
    label: 'planuri coordonatoare goluri',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a17',
    position: { x: 615, y: 1978 },
    label: 'planuri pentru vânzări',
    className: 'proiectare-flow primary',
  },
  {
    id: 'a18',
    position: { x: 598.5, y: 2058 },
    label: 'planuri PT pentru execuție',
    className: 'proiectare-flow primary w-[242px]',
  },
  {
    id: 'a19',
    position: { x: 634, y: 2118 },
    label: 'liste de cantități',
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a20',
    position: { x: 634, y: 2198 },
    label: 'detalii de execuție',
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a21',
    position: { x: 634, y: 2258 },
    label: 'piese scrise',
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a22',
    position: { x: 599, y: 2318 },
    label: 'planuri revizuite (feedback execuție)',
    className: 'proiectare-flow primary w-[240px]',
  },
  {
    id: 'a23',
    position: { x: 634, y: 2398 },
    label: 'planuri AS-BUILT',
    className: 'proiectare-flow primary w-[170px]',
  },

  /* ───────────── STRUCTURĂ  ───────────── */
  {
    id: 's1',
    position: { x: 930, y: 106 },
    label: 'analiză geometrică structură',
    className: 'proiectare-flow orange',
  },
  {
    id: 's2',
    position: { x: 986, y: 527 },
    label: 'concept structură',
    className: 'proiectare-flow orange',
  },
  {
    id: 's3',
    position: { x: 970, y: 667 },
    label: 'planuri cofraj propuse',
    className: 'proiectare-flow orange',
  },
  {
    id: 's4',
    position: { x: 1027.5, y: 910 },
    label: 'expertize',
    className: 'proiectare-flow orange',
  },
  {
    id: 's5',
    position: { x: 926, y: 1290 },
    label: 'planuri cofraj DTAC',
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's6',
    position: { x: 926, y: 1350 },
    label: 'planuri excavație + incintă',
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's7',
    position: { x: 926, y: 1410 },
    label: 'liste cantități preliminare',
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's8',
    position: { x: 926, y: 1470 },
    label: 'calcul armare elemente verticale',
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's9',
    position: { x: 926, y: 1530 },
    label: 'planuri armare elemente verticale',
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's10',
    position: { x: 994, y: 1797 },
    label: 'planuri cofraj PT',
    className: 'proiectare-flow orange',
  },
  {
    id: 's11',
    position: { x: 960, y: 1857 },
    label: 'planuri armare grinzi + plăci supra',
    className: 'proiectare-flow orange w-[180px]',
  },
  {
    id: 's12',
    position: { x: 960, y: 1937 },
    label: 'planuri borduri goluri + detalii',
    className: 'proiectare-flow orange w-[180px]',
  },
  {
    id: 's13',
    position: { x: 960, y: 2073 },
    label: 'planuri armare grinzi, plăci + rampe infra',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's14',
    position: { x: 960, y: 2200 },
    label: 'planuri cofraj + armare fundații',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's15',
    position: { x: 960, y: 2280 },
    label: 'planuri cofraj + armare spații comune',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's16',
    position: { x: 960, y: 2360 },
    label: 'planuri cofraj + armare scări duplex',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's17',
    position: { x: 960, y: 2440 },
    label: 'planuri armare elemente speciale beton',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's18',
    position: { x: 960, y: 2520 },
    label: 'plan poziționare elemente beton în zone',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's19',
    position: { x: 960, y: 2600 },
    label: 'plan structuri metalice secundare',
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's20',
    position: { x: 985, y: 2680 },
    label: 'liste de cantități',
    className: 'proiectare-flow orange w-[185px]',
  },
  {
    id: 's21',
    position: { x: 985, y: 2740 },
    label: 'piese scrise',
    className: 'proiectare-flow orange w-[185px]',
  },
  {
    id: 's22',
    position: { x: 985, y: 2800 },
    label: 'dispoziție de șantier',
    className: 'proiectare-flow orange w-[185px]',
  },
];
const getEdges = () => [
  /*  1 */ {
    id: 'd1-i1',
    source: 'd1',
    target: 'i1',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  2 */ {
    id: 'd1-a1',
    source: 'd1',
    target: 'a1',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  3 */ {
    id: 'd2-a2',
    source: 'd2',
    target: 'a2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  4 */ {
    id: 'd3-a3',
    source: 'd3',
    target: 'a3',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  5 */ {
    id: 'd4-i2',
    source: 'd4',
    target: 'i2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  6 */ {
    id: 'a3-i2',
    source: 'a3',
    target: 'i2',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  7 */ {
    id: 'a1-a2',
    source: 'a1',
    target: 'a2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  8 */ {
    id: 'a2-a3',
    source: 'a2',
    target: 'a3',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*  9 */ {
    id: 'a1-s1',
    source: 'a1',
    target: 's1',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 10 */ {
    id: 's1-a1',
    source: 's1',
    target: 'a1',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 11 */ {
    id: 'a3-a4',
    source: 'a3',
    target: 'a4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 12 */ {
    id: 'i2-a4',
    source: 'i2',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 13 */ {
    id: 'd5-a4',
    source: 'd5',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 14 */ {
    id: 'd6-a4',
    source: 'd6',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-3',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 15 */ {
    id: 'a4-i3',
    source: 'a4',
    target: 'i3',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 16 */ {
    id: 'a4-s2',
    source: 'a4',
    target: 's2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 17 */ {
    id: 'd19-s2',
    source: 'd19',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 18 */ {
    id: 'd20-s2',
    source: 'd20',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 19 */ {
    id: 'd21-s2',
    source: 'd21',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 20 */ {
    id: 'a4-a5',
    source: 'a4',
    target: 'a5',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 21 */ {
    id: 'i3-a5',
    source: 'i3',
    target: 'a5',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 22 */ {
    id: 's2-a5',
    source: 's2',
    target: 'a5',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 23 */ {
    id: 'd7-a5',
    source: 'd7',
    target: 'a5',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 24 */ {
    id: 'd22-a5',
    source: 'd22',
    target: 'a5',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 25 */ {
    id: 'a5-i4',
    source: 'a5',
    target: 'i4',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 26 */ {
    id: 'a5-s3',
    source: 'a5',
    target: 's3',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 27 */ {
    id: 's3-s4',
    source: 's3',
    target: 's4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 28 */ {
    id: 'a12.2-s3',
    source: 'a12.2',
    target: 's3',
    sourceHandle: 'right',
    targetHandle: 'left-top',
    type: 'step',
    style: { stroke: '#000', strokeDasharray: '6 3' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 29 */ {
    id: 's3-a12.3',
    source: 's3',
    target: 'a12.3',
    sourceHandle: 'left-bottom',
    targetHandle: 'right',
    type: 'cofraj-step',
    style: { stroke: '#000', strokeDasharray: '6 3' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 30 */ {
    id: 's4-s5',
    source: 's4',
    target: 's5',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 31 */ {
    id: 's5-s6',
    source: 's5',
    target: 's6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 32 */ {
    id: 's6-s7',
    source: 's6',
    target: 's7',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 33 */ {
    id: 's7-s8',
    source: 's7',
    target: 's8',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 34 */ {
    id: 's8-s9',
    source: 's8',
    target: 's9',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 35 */ {
    id: 's9-s10',
    source: 's9',
    target: 's10',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 36 */ {
    id: 's10-a15',
    source: 's10',
    target: 'a15',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 37 */ {
    id: 's10-s11',
    source: 's10',
    target: 's11',
    sourceHandle: 'left',
    targetHandle: 'left-top-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 38 */ {
    id: 's10-s12',
    source: 's10',
    target: 's12',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 39 */ {
    id: 's10-s13',
    source: 's10',
    target: 's13',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 40 */ {
    id: 's10-s14',
    source: 's10',
    target: 's14',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 41 */ {
    id: 's10-s15',
    source: 's10',
    target: 's15',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 42 */ {
    id: 's10-s16',
    source: 's10',
    target: 's16',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 43 */ {
    id: 's10-s17',
    source: 's10',
    target: 's17',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 44 */ {
    id: 's10-s18',
    source: 's10',
    target: 's18',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 45 */ {
    id: 's10-s19',
    source: 's10',
    target: 's19',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 46 */ {
    id: 's19-s20',
    source: 's19',
    target: 's20',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 47 */ {
    id: 's20-s21',
    source: 's20',
    target: 's21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 48 */ {
    id: 's21-s22',
    source: 's21',
    target: 's22',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 49 */ {
    id: 'a5-a6',
    source: 'a5',
    target: 'a6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 50 */ {
    id: 'i4-a6',
    source: 'i4',
    target: 'a6',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 51 */ {
    id: 'a6-d8',
    source: 'a6',
    target: 'd8',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 52 */ {
    id: 'a6-a8',
    source: 'a6',
    target: 'a8',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 53 */ {
    id: 'a6-a9',
    source: 'a6',
    target: 'a9',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 54 */ {
    id: 'a6-a10',
    source: 'a6',
    target: 'a10',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 55 */ {
    id: 'a6-a11',
    source: 'a6',
    target: 'a11',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 56 */ {
    id: 'd8-d9',
    source: 'd8',
    target: 'd9',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 57 */ {
    id: 'd9-d10',
    source: 'd9',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 58 */ {
    id: 'i5-d10',
    source: 'i5',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 59 */ {
    id: 'a7-d10',
    source: 'a7',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 60 */ {
    id: 'd11-a10',
    source: 'd11',
    target: 'a10',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 61 */ {
    id: 'i6-a8',
    source: 'i6',
    target: 'a8',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 62 */ {
    id: 'i6-a9',
    source: 'i6',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 63 */ {
    id: 'd23-a9',
    source: 'd23',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'right-top',
    type: 'avize-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 64 */ {
    id: 'd24-a9',
    source: 'd24',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'right-bottom',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 65 */ {
    id: 'd25-a12',
    source: 'd25',
    target: 'a12',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 66 */ {
    id: 'd26-s6',
    source: 'd26',
    target: 's6',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 67 */ {
    id: 's5-a12',
    source: 's5',
    target: 'a12',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 68 */ {
    id: 'a12-s5',
    source: 'a12',
    target: 's5',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 69 */ {
    id: 'd12-i7',
    source: 'd12',
    target: 'i7',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 70 */ {
    id: 'a10-i8',
    source: 'a10',
    target: 'i8',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 71 */ {
    id: 'i7-i9',
    source: 'i7',
    target: 'i9',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 72 */ {
    id: 'i7-i10',
    source: 'i7',
    target: 'i10',
    sourceHandle: 'right',
    targetHandle: 'right-top-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 73 */ {
    id: 'a12-d13',
    source: 'a12',
    target: 'd13',
    sourceHandle: 'left-bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 74 */ {
    id: 'd13-d14',
    source: 'd13',
    target: 'd14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 75 */ {
    id: 'a11-a12',
    source: 'a11',
    target: 'a12',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 76 */ {
    id: 'a12-a13',
    source: 'a12',
    target: 'a13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'fisa-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 77 */ {
    id: 'a12-a12.1',
    source: 'a12',
    target: 'a12.1',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 78 */ {
    id: 'a12.1-a12.2',
    source: 'a12.1',
    target: 'a12.2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 79 */ {
    id: 'a12.2-a12.3',
    source: 'a12.2',
    target: 'a12.3',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 80 */ {
    id: 'a12.3-a12.4',
    source: 'a12.3',
    target: 'a12.4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 81 */ {
    id: 'a12.4-a13',
    source: 'a12.4',
    target: 'a13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 82 */ {
    id: 'a13-a14.1',
    source: 'a13',
    target: 'a14.1',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 83 */ {
    id: 'a13-a14.2',
    source: 'a13',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 84 */ {
    id: 'a14.1-a15',
    source: 'a14.1',
    target: 'a15',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'short-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 85 */ {
    id: 'a14.2-a15',
    source: 'a14.2',
    target: 'a15',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'short-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 86 */ {
    id: 'a15-a16',
    source: 'a15',
    target: 'a16',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 87 */ {
    id: 'a16-a17',
    source: 'a16',
    target: 'a17',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 88 */ {
    id: 'a17-a18',
    source: 'a17',
    target: 'a18',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 89 */ {
    id: 'a18-a19',
    source: 'a18',
    target: 'a19',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 90 */ {
    id: 'a18-a22',
    source: 'a18',
    target: 'a22',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 91 */ {
    id: 'a19-a20',
    source: 'a19',
    target: 'a20',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 92 */ {
    id: 'a20-a21',
    source: 'a20',
    target: 'a21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 93 */ {
    id: 'a22-a23',
    source: 'a22',
    target: 'a23',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 94 */ {
    id: 'd29-a18',
    source: 'd29',
    target: 'a18',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 95 */ {
    id: 'd30-a20',
    source: 'd30',
    target: 'a20',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 96 */ {
    id: 'd14-a14.1',
    source: 'd14',
    target: 'a14.1',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'short-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 97 */ {
    id: 'd14-a14.2',
    source: 'd14',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'short-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 98 */ {
    id: 'd15-i11',
    source: 'd15',
    target: 'i11',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /* 99 */ {
    id: 'a14.1-i11',
    source: 'a14.1',
    target: 'i11',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*100 */ {
    id: 'i11-a15',
    source: 'i11',
    target: 'a15',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*101*/ {
    id: 'd16-a15',
    source: 'd16',
    target: 'a15',
    sourceHandle: 'right',
    targetHandle: 'left-top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*102*/ {
    id: 'i12-d17',
    source: 'i12',
    target: 'd17',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*103*/ {
    id: 'i12-i13',
    source: 'i12',
    target: 'i13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*104*/ {
    id: 'i13-i14',
    source: 'i13',
    target: 'i14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*105*/ {
    id: 'i14-i15',
    source: 'i14',
    target: 'i15',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*106*/ {
    id: 'i15-i16',
    source: 'i15',
    target: 'i16',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*107*/ {
    id: 'i13-d17',
    source: 'i13',
    target: 'd17',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*108*/ {
    id: 'a15-i12',
    source: 'a15',
    target: 'i12',
    sourceHandle: 'bottom-left-1',
    targetHandle: 'right',
    type: 'coordonatoare-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*109*/ {
    id: 'a15-i13',
    source: 'a15',
    target: 'i13',
    sourceHandle: 'bottom-left-1',
    targetHandle: 'right',
    type: 'coordonatoare-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*110*/ {
    id: 'd17-i16',
    source: 'd17',
    target: 'i16',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*111*/ {
    id: 'd18-i16',
    source: 'd18',
    target: 'i16',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*112*/ {
    id: 'i16-i17',
    source: 'i16',
    target: 'i17',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*113*/ {
    id: 'i16-i18',
    source: 'i16',
    target: 'i18',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*114*/ {
    id: 'i16-i19',
    source: 'i16',
    target: 'i19',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*115*/ {
    id: 'i14-a16',
    source: 'i14',
    target: 'a16',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'goluri-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*116*/ {
    id: 'a14.2-s10',
    source: 'a14.2',
    target: 's10',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*117*/ {
    id: 'd28-s10',
    source: 'd28',
    target: 's10',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*118*/ {
    id: 'd27-a14.2',
    source: 'd27',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-2',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*119*/ {
    id: 'd9-a12',
    source: 'd9',
    target: 'a12',
    sourceHandle: 'right-top',
    targetHandle: 'left-top',
    type: 'goluri-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*120*/ {
    id: 'd9-i10',
    source: 'd9',
    target: 'i10',
    sourceHandle: 'right-bottom',
    targetHandle: 'left',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*121*/ {
    id: 'i10-s10',
    source: 'i10',
    target: 's10',
    sourceHandle: 'right-top-1',
    targetHandle: 'left',
    type: 'goluri-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*122*/ {
    id: 'i10-a15',
    source: 'i10',
    target: 'a15',
    sourceHandle: 'right-bottom-1',
    targetHandle: 'left-bottom',
    type: 'infra-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*123*/ {
    id: 'i10-s11',
    source: 'i10',
    target: 's11',
    sourceHandle: 'right-bottom-2',
    targetHandle: 'left',
    type: 'infra-step2',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*124*/ {
    id: 'd10-i9',
    source: 'd10',
    target: 'i9',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'nzeb-step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*125*/ {
    id: 'd10-a12',
    source: 'd10',
    target: 'a12',
    sourceHandle: 'right-bottom',
    targetHandle: 'left',
    type: 'nzeb-step2',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*126*/ {
    id: 's5-i8',
    source: 's5',
    target: 'i8',
    sourceHandle: 'left-bottom',
    targetHandle: 'right-top',
    type: 'cofraj-step2',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
  /*127*/ {
    id: 'i8-s6',
    source: 'i8',
    target: 's6',
    sourceHandle: 'right-bottom',
    targetHandle: 'left-top',
    type: 'step',
    style: { stroke: '#000' },
    markerEnd: { type: 'arrowclosed', color: '#000' },
  },
];
const permission = 'remedieri';

/* ---------- nodes -------------------------------------------------- */
const getMiniNodes = () => [
  {
    id: '1',
    label: 'Recepția cu clienții',
    link: '/flow/receptie-clienti',
    position: { x: 10, y: 15 },
    cssClass: 'mini-flow primary w-56',
    permission,
    showIndex: true,
  },
  {
    id: '2',
    label: 'Predarea clădirii către clienți',
    link: null,
    position: { x: 120, y: 80 },
    cssClass: 'mini-flow primary w-[265px]',
    permission,
    showIndex: true,
  },
  {
    id: '3',
    label: 'Remedierile în garanție',
    link: null, // current page
    position: { x: 311, y: 15 },
    cssClass: 'mini-flow green w-52',
    permission,
    showIndex: true,
  },
];

/* ---------- edges -------------------------------------------------- */
const defaultEdgeStyle = { stroke: '#374151', strokeWidth: 1.3 };
const defaultMarker = { type: 'arrow', color: '#374151', width: 13, height: 13 };

const getMiniEdges = () => [
  {
    id: '1-3',
    source: '1',
    target: '3',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
    permission,
    showIndex: true,
  },
  {
    id: '2-3',
    source: '2',
    target: '3',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'step',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
    permission,
    showIndex: true,
  },
];

module.exports = { getNodes, getEdges, getMiniEdges, getMiniNodes, permission: 'remedieri' };
