const defaultEdgeProps = {
  markerEnd: { type: 'arrowclosed', color: '#000' },
  style: { stroke: '#000' },
};
const permission = '3';
const addEdge = (edge) => ({
  ...defaultEdgeProps,
  type: 'step', // default – override per-edge if needed
  ...edge,
});
const getEdges = () => [
  addEdge({
    id: 'd1-i1',
    source: 'd1',
    target: 'i1',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'd1-a1',
    source: 'd1',
    target: 'a1',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'd2-a2',
    source: 'd2',
    target: 'a2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'd3-a3',
    source: 'd3',
    target: 'a3',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'd4-i2',
    source: 'd4',
    target: 'i2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'a3-i2',
    source: 'a3',
    target: 'i2',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({ id: 'a1-a2', source: 'a1', target: 'a2', sourceHandle: 'bottom', targetHandle: 'top' }),
  addEdge({
    id: 'a2-a3',
    source: 'a2',
    target: 'a3',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a1-s1',
    source: 'a1',
    target: 's1',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's1-a1',
    source: 's1',
    target: 'a1',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'a3-a4',
    source: 'a3',
    target: 'a4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'i2-a4',
    source: 'i2',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'd5-a4',
    source: 'd5',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
  }),
  addEdge({
    id: 'd6-a4',
    source: 'd6',
    target: 'a4',
    sourceHandle: 'right',
    targetHandle: 'top-left-3',
    type: 'step',
  }),
  addEdge({
    id: 'a4-i3',
    source: 'a4',
    target: 'i3',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a4-s2',
    source: 'a4',
    target: 's2',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),

  addEdge({
    id: 'd19-s2',
    source: 'd19',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'd20-s2',
    source: 'd20',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'd21-s2',
    source: 'd21',
    target: 's2',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
  }),

  addEdge({
    id: 'a4-a5',
    source: 'a4',
    target: 'a5',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'i3-a5',
    source: 'i3',
    target: 'a5',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 's2-a5',
    source: 's2',
    target: 'a5',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'd7-a5',
    source: 'd7',
    target: 'a5',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
  }),
  addEdge({
    id: 'd22-a5',
    source: 'd22',
    target: 'a5',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
  }),

  addEdge({
    id: 'a5-i4',
    source: 'a5',
    target: 'i4',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a5-s3',
    source: 'a5',
    target: 's3',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 's3-s4',
    source: 's3',
    target: 's4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'a12.2-s3',
    source: 'a12.2',
    target: 's3',
    sourceHandle: 'right',
    targetHandle: 'left-top',
    type: 'step',
    style: { strokeDasharray: '6 3', stroke: '#000' },
  }),

  addEdge({
    id: 's3-a12.3',
    source: 's3',
    target: 'a12.3',
    sourceHandle: 'left-bottom',
    targetHandle: 'right',
    type: 'cofraj-step',
    style: { strokeDasharray: '6 3', stroke: '#000' },
  }),

  addEdge({
    id: 's4-s5',
    source: 's4',
    target: 's5',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's5-s5',
    source: 's5',
    target: 's6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's6-s7',
    source: 's6',
    target: 's7',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's7-s8',
    source: 's7',
    target: 's8',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's8-s9',
    source: 's8',
    target: 's9',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's9-s10',
    source: 's9',
    target: 's10',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),

  addEdge({
    id: 's10-a15',
    source: 's10',
    target: 'a15',
    sourceHandle: 'left',
    targetHandle: 'top-right-2',
    type: 'step',
  }),
  addEdge({
    id: 's10-s11',
    source: 's10',
    target: 's11',
    sourceHandle: 'left',
    targetHandle: 'left-top-2',
    type: 'step',
  }),
  addEdge({
    id: 's10-s12',
    source: 's10',
    target: 's12',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s13',
    source: 's10',
    target: 's13',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s14',
    source: 's10',
    target: 's14',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s15',
    source: 's10',
    target: 's15',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s16',
    source: 's10',
    target: 's16',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s17',
    source: 's10',
    target: 's17',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s18',
    source: 's10',
    target: 's18',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's10-s19',
    source: 's10',
    target: 's19',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 's19-s20',
    source: 's19',
    target: 's20',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's20-s21',
    source: 's20',
    target: 's21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 's21-s22',
    source: 's21',
    target: 's22',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),

  addEdge({
    id: 'a5-a6',
    source: 'a5',
    target: 'a6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'i4-a6',
    source: 'i4',
    target: 'a6',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),

  addEdge({
    id: 'a6-d8',
    source: 'a6',
    target: 'd8',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a6-a8',
    source: 'a6',
    target: 'a8',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'a6-a9',
    source: 'a6',
    target: 'a9',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'a6-a10',
    source: 'a6',
    target: 'a10',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'a6-a11',
    source: 'a6',
    target: 'a11',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
  }),

  addEdge({
    id: 'd8-d9',
    source: 'd8',
    target: 'd9',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'd9-d10',
    source: 'd9',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'i5-d10',
    source: 'i5',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'a7-d10',
    source: 'a7',
    target: 'd10',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-2',
    type: 'step',
  }),

  addEdge({
    id: 'd11-a10',
    source: 'd11',
    target: 'a10',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'i6-a8',
    source: 'i6',
    target: 'a8',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 'i6-a9',
    source: 'i6',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  }),

  addEdge({
    id: 'd23-a9',
    source: 'd23',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'right-top',
    type: 'avize-step',
  }),
  addEdge({
    id: 'd24-a9',
    source: 'd24',
    target: 'a9',
    sourceHandle: 'bottom',
    targetHandle: 'right-bottom',
    type: 'step',
  }),
  addEdge({
    id: 'd25-a12',
    source: 'd25',
    target: 'a12',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'd26-s6',
    source: 'd26',
    target: 's6',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
  }),

  addEdge({
    id: 's5-a12',
    source: 's5',
    target: 'a12',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'a12-s5',
    source: 'a12',
    target: 's5',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  }),

  addEdge({
    id: 'd12-i7',
    source: 'd12',
    target: 'i7',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),

  addEdge({
    id: 'a10-i8',
    source: 'a10',
    target: 'i8',
    sourceHandle: 'left',
    targetHandle: 'right',
    type: 'step',
  }),

  addEdge({
    id: 'i7-i9',
    source: 'i7',
    target: 'i9',
    sourceHandle: 'right',
    targetHandle: 'right',
    type: 'step',
  }),
  addEdge({
    id: 'i7-i10',
    source: 'i7',
    target: 'i10',
    sourceHandle: 'right',
    targetHandle: 'right-top-2',
    type: 'step',
  }),

  addEdge({
    id: 'a12-d13',
    source: 'a12',
    target: 'd13',
    sourceHandle: 'left-bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'd13-d14',
    source: 'd13',
    target: 'd14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),

  addEdge({
    id: 'a11-a12',
    source: 'a11',
    target: 'a12',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'a12-a13',
    source: 'a12',
    target: 'a13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'fisa-step',
  }),

  addEdge({
    id: 'a12-a12.1',
    source: 'a12',
    target: 'a12.1',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a12.1-a12.2',
    source: 'a12.1',
    target: 'a12.2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a12.2-a12.3',
    source: 'a12.2',
    target: 'a12.3',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a12.3-a12.4',
    source: 'a12.3',
    target: 'a12.4',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a12.4-a13',
    source: 'a12.4',
    target: 'a13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'a13-a14.1',
    source: 'a13',
    target: 'a14.1',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'a13-a14.2',
    source: 'a13',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),

  addEdge({
    id: 'a14.1-a15',
    source: 'a14.1',
    target: 'a15',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'short-step',
  }),
  addEdge({
    id: 'a14.2-a15',
    source: 'a14.2',
    target: 'a15',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'short-step',
  }),
  addEdge({
    id: 'a15-a16',
    source: 'a15',
    target: 'a16',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a16-a17',
    source: 'a16',
    target: 'a17',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a17-a18',
    source: 'a17',
    target: 'a18',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a18-a19',
    source: 'a18',
    target: 'a19',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a18-a22',
    source: 'a18',
    target: 'a22',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 'a19-a20',
    source: 'a19',
    target: 'a20',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a20-a21',
    source: 'a20',
    target: 'a21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'a22-a23',
    source: 'a22',
    target: 'a23',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),

  addEdge({
    id: 'd29-a18',
    source: 'd29',
    target: 'a18',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'd30-a20',
    source: 'd30',
    target: 'a20',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),

  addEdge({
    id: 'd14-a14.1',
    source: 'd14',
    target: 'a14.1',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'short-step',
  }),
  addEdge({
    id: 'd14-a14.2',
    source: 'd14',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-1',
    type: 'short-step',
  }),

  addEdge({
    id: 'd15-i11',
    source: 'd15',
    target: 'i11',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'a14.1-i11',
    source: 'a14.1',
    target: 'i11',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),
  addEdge({
    id: 'i11-a15',
    source: 'i11',
    target: 'a15',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
  }),

  addEdge({
    id: 'd16-a15',
    source: 'd16',
    target: 'a15',
    sourceHandle: 'right',
    targetHandle: 'left-top',
    type: 'step',
  }),

  addEdge({
    id: 'i12-d17',
    source: 'i12',
    target: 'd17',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'i12-i13',
    source: 'i12',
    target: 'i13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'i13-i14',
    source: 'i13',
    target: 'i14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'i14-i15',
    source: 'i14',
    target: 'i15',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  }),
  addEdge({
    id: 'i15-i16',
    source: 'i15',
    target: 'i16',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  }),
  addEdge({
    id: 'i13-d17',
    source: 'i13',
    target: 'd17',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),

  addEdge({
    id: 'a15-i12',
    source: 'a15',
    target: 'i12',
    sourceHandle: 'bottom-left-1',
    targetHandle: 'right',
    type: 'coordonatoare-step',
  }),
  addEdge({
    id: 'a15-i13',
    source: 'a15',
    target: 'i13',
    sourceHandle: 'bottom-left-1',
    targetHandle: 'right',
    type: 'coordonatoare-step',
  }),

  addEdge({
    id: 'd17-i16',
    source: 'd17',
    target: 'i16',
    sourceHandle: 'bottom',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'd18-i16',
    source: 'd18',
    target: 'i16',
    sourceHandle: 'right',
    targetHandle: 'top-left-2',
    type: 'step',
  }),

  addEdge({
    id: 'i16-i17',
    source: 'i16',
    target: 'i17',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 'i16-i18',
    source: 'i16',
    target: 'i18',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),
  addEdge({
    id: 'i16-i19',
    source: 'i16',
    target: 'i19',
    sourceHandle: 'left',
    targetHandle: 'left',
    type: 'step',
  }),

  addEdge({
    id: 'i14-a16',
    source: 'i14',
    target: 'a16',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'goluri-step',
  }),

  addEdge({
    id: 'a14.2-s10',
    source: 'a14.2',
    target: 's10',
    sourceHandle: 'right',
    targetHandle: 'top-left-1',
    type: 'step',
  }),
  addEdge({
    id: 'd28-s10',
    source: 'd28',
    target: 's10',
    sourceHandle: 'left',
    targetHandle: 'top-right-1',
    type: 'step',
  }),

  addEdge({
    id: 'd27-a14.2',
    source: 'd27',
    target: 'a14.2',
    sourceHandle: 'bottom',
    targetHandle: 'top-right-2',
    type: 'step',
  }),

  addEdge({
    id: 'd9-a12',
    source: 'd9',
    target: 'a12',
    sourceHandle: 'right-top',
    targetHandle: 'left-top',
    type: 'goluri-step',
  }),
  addEdge({
    id: 'd9-i10',
    source: 'd9',
    target: 'i10',
    sourceHandle: 'right-bottom',
    targetHandle: 'left',
    type: 'step',
  }),

  addEdge({
    id: 'i10-s10',
    source: 'i10',
    target: 's10',
    sourceHandle: 'right-top-1',
    targetHandle: 'left',
    type: 'goluri-step',
  }),
  addEdge({
    id: 'i10-a15',
    source: 'i10',
    target: 'a15',
    sourceHandle: 'right-bottom-1',
    targetHandle: 'left-bottom',
    type: 'infra-step',
  }),
  addEdge({
    id: 'i10-s11',
    source: 'i10',
    target: 's11',
    sourceHandle: 'right-bottom-2',
    targetHandle: 'left',
    type: 'infra-step2',
  }),

  addEdge({
    id: 'd10-i9',
    source: 'd10',
    target: 'i9',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'nzeb-step',
  }),
  addEdge({
    id: 'd10-a12',
    source: 'd10',
    target: 'a12',
    sourceHandle: 'right-bottom',
    targetHandle: 'left',
    type: 'nzeb-step2',
  }),

  addEdge({
    id: 's5-i8',
    source: 's5',
    target: 'i8',
    sourceHandle: 'left-bottom',
    targetHandle: 'right-top',
    type: 'cofraj-step2',
  }),

  addEdge({
    id: 'i8-s6',
    source: 'i8',
    target: 's6',
    sourceHandle: 'right-bottom',
    targetHandle: 'left-top',
    type: 'step',
  }),
];

const nodePositions = [
  { id: 'd1', position: { x: 20, y: 55 } },
  { id: 'd2', position: { x: 20, y: 135 } },
  { id: 'd3', position: { x: 20, y: 215 } },
  { id: 'd4', position: { x: 7, y: 295 } },
  { id: 'd5', position: { x: 20, y: 355 } },
  { id: 'd6', position: { x: 1, y: 435 } },
  { id: 'd7', position: { x: 2, y: 575 } },
  { id: 'd8', position: { x: 9, y: 749 } },
  { id: 'd9', position: { x: 25, y: 810 } },
  { id: 'd10', position: { x: 40.2, y: 930 } },
  { id: 'd11', position: { x: 25, y: 1049 } },
  { id: 'd12', position: { x: 35, y: 1129 } },
  { id: 'd13', position: { x: 13, y: 1431 } },
  { id: 'd14', position: { x: 24.5, y: 1491 } },
  { id: 'd15', position: { x: 15, y: 1736 } },
  { id: 'd16', position: { x: 15, y: 1820 } },
  { id: 'd17', position: { x: 24, y: 2011 } },
  { id: 'd18', position: { x: 15, y: 2195 } },
  { id: 'd19', position: { x: 1245, y: 356 } },
  { id: 'd20', position: { x: 1245, y: 416 } },
  { id: 'd21', position: { x: 1245, y: 476 } },
  { id: 'd22', position: { x: 1255, y: 565 } },
  { id: 'd23', position: { x: 1252, y: 725 } },
  { id: 'd24', position: { x: 1252, y: 900 } },
  { id: 'd25', position: { x: 1265, y: 1249 } },
  { id: 'd26', position: { x: 1254, y: 1340 } },
  { id: 'd27', position: { x: 1254, y: 1634 } },
  { id: 'd28', position: { x: 1254, y: 1736 } },
  { id: 'd29', position: { x: 1260, y: 2017 } },
  { id: 'd30', position: { x: 1255, y: 2157 } },

  { id: 'i1', position: { x: 257, y: 106 } },
  { id: 'i2', position: { x: 215, y: 336 } },
  { id: 'i3', position: { x: 253, y: 517 } },
  { id: 'i4', position: { x: 224, y: 667 } },
  { id: 'i5', position: { x: 256.5, y: 780 } },
  { id: 'i6', position: { x: 238.5, y: 976 } },
  { id: 'i7', position: { x: 245.5, y: 1270 } },
  { id: 'i8', position: { x: 245.5, y: 1330 } },
  { id: 'i9', position: { x: 245.5, y: 1390 } },
  { id: 'i10', position: { x: 290, y: 1600 } },
  { id: 'i11', position: { x: 255, y: 1797 } },
  { id: 'i12', position: { x: 252, y: 1868.8 } },
  { id: 'i13', position: { x: 252, y: 1960 } },
  { id: 'i14', position: { x: 224.5, y: 2040 } },
  { id: 'i15', position: { x: 272, y: 2100 } },
  { id: 'i16', position: { x: 257, y: 2277 } },
  { id: 'i17', position: { x: 257, y: 2357 } },
  { id: 'i18', position: { x: 257, y: 2417 } },
  { id: 'i19', position: { x: 257, y: 2477 } },

  { id: 'a1', position: { x: 653.4, y: 106 } },
  { id: 'a2', position: { x: 559.8, y: 186 } },
  { id: 'a3', position: { x: 630.4, y: 295 } },
  { id: 'a4', position: { x: 595.5, y: 476 } },
  { id: 'a5', position: { x: 617.4, y: 626 } },
  { id: 'a6', position: { x: 602, y: 708 } },
  { id: 'a7', position: { x: 614, y: 847 } },
  { id: 'a8', position: { x: 600, y: 930 } },
  { id: 'a9', position: { x: 602, y: 1007 } },
  { id: 'a10', position: { x: 602, y: 1100 } },
  { id: 'a11', position: { x: 601.9, y: 1180 } },
  { id: 'a12', position: { x: 604.5, y: 1290 } },
  { id: 'a12.1', position: { x: 530, y: 1382 } },
  { id: 'a12.2', position: { x: 530, y: 1442 } },
  { id: 'a12.3', position: { x: 530, y: 1502 } },
  { id: 'a12.4', position: { x: 530, y: 1562 } },
  { id: 'a13', position: { x: 650, y: 1654 } },
  { id: 'a14', position: { x: 530, y: 2015 } },
  { id: 'a14.1', position: { x: 526, y: 1736 } },
  { id: 'a14.2', position: { x: 724, y: 1736 } },
  { id: 'a15', position: { x: 613, y: 1838 } },
  { id: 'a16', position: { x: 585, y: 1918 } },
  { id: 'a17', position: { x: 615, y: 1978 } },
  { id: 'a18', position: { x: 598.5, y: 2058 } },
  { id: 'a19', position: { x: 634, y: 2118 } },
  { id: 'a20', position: { x: 634, y: 2198 } },
  { id: 'a21', position: { x: 634, y: 2258 } },
  { id: 'a22', position: { x: 599, y: 2318 } },
  { id: 'a23', position: { x: 634, y: 2398 } },

  { id: 's1', position: { x: 930, y: 106 } },
  { id: 's2', position: { x: 986, y: 527 } },
  { id: 's3', position: { x: 970, y: 667 } },
  { id: 's4', position: { x: 1027.5, y: 910 } },
  { id: 's5', position: { x: 926, y: 1290 } },
  { id: 's6', position: { x: 926, y: 1350 } },
  { id: 's7', position: { x: 926, y: 1410 } },
  { id: 's8', position: { x: 926, y: 1470 } },
  { id: 's9', position: { x: 926, y: 1530 } },
  { id: 's10', position: { x: 994, y: 1797 } },
  { id: 's11', position: { x: 960, y: 1857 } },
  { id: 's12', position: { x: 960, y: 1937 } },
  { id: 's13', position: { x: 960, y: 2073 } },
  { id: 's14', position: { x: 960, y: 2200 } },
  { id: 's15', position: { x: 960, y: 2280 } },
  { id: 's16', position: { x: 960, y: 2360 } },
  { id: 's17', position: { x: 960, y: 2440 } },
  { id: 's18', position: { x: 960, y: 2520 } },
  { id: 's19', position: { x: 960, y: 2600 } },
  { id: 's20', position: { x: 985, y: 2680 } },
  { id: 's21', position: { x: 985, y: 2740 } },
  { id: 's22', position: { x: 985, y: 2800 } },
];

const getNodePosition = (id) => {
  const node = nodePositions.find((n) => n.id === id);
  return node ? node.position : { x: 0, y: 0 };
};

const getNodes = () => [
  {
    id: 'd1',
    position: getNodePosition('d1'),
    data: {
      label: 'temă+documente analiză teren',
    },
    className: 'proiectare-flow extern w-[160px]',
  },
  {
    id: 'd2',
    position: getNodePosition('d2'),
    data: {
      label: 'documente teren pentru CU',
    },
    className: 'proiectare-flow extern w-[160px]',
  },
  {
    id: 'd3',
    position: getNodePosition('d3'),
    data: {
      label: 'temă proiectare concept',
    },
    className: 'proiectare-flow extern w-[160px]',
  },
  {
    id: 'd4',
    position: getNodePosition('d4'),
    data: {
      label: 'temă soluții tehnice',
    },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd5',
    position: getNodePosition('d5'),
    data: {
      label: 'listă cerințe preliminare NZEB',
    },
    className: 'proiectare-flow extern w-[160px]',
  },
  {
    id: 'd6',
    position: getNodePosition('d6'),
    data: {
      label: 'decizie fazare proiect',
    },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd7',
    position: getNodePosition('d7'),
    data: { label: 'feedback dezvoltare și vânzări' },
    className: 'proiectare-flow extern w-[194px]',
  },
  {
    id: 'd8',
    position: getNodePosition('d8'),
    data: { label: 'concept spații verzi' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd9',
    position: getNodePosition('d9'),
    data: { label: 'concept sistematizare' },
    className: 'proiectare-flow extern w-[150px]',
  },
  {
    id: 'd10',
    position: getNodePosition('d10'),
    data: { label: 'raport NZEB' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd11',
    position: getNodePosition('d11'),
    data: { label: 'decizii aspecte interpretabile' },
    className: 'proiectare-flow extern w-[150px]',
  },
  {
    id: 'd12',
    position: getNodePosition('d12'),
    data: { label: 'aviz Apa Nova' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd13',
    position: getNodePosition('d13'),
    data: { label: 'proiect spații verzi' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd14',
    position: getNodePosition('d14'),
    data: { label: 'proiect sistematizare' },
    className: 'proiectare-flow extern w-[150px]',
  },

  {
    id: 'd15',
    position: getNodePosition('d15'),
    data: { label: 'temă materiale + soluții supra' },
    className: 'proiectare-flow extern w-[150px]',
  },
  {
    id: 'd16',
    position: getNodePosition('d16'),
    data: { label: 'temă finisaje arhitecturale' },
    className: 'proiectare-flow extern w-[150px]',
  },
  {
    id: 'd17',
    position: getNodePosition('d17'),
    data: { label: 'validare echipamente' },
    className: 'proiectare-flow extern w-[150px]',
  },
  {
    id: 'd18',
    position: getNodePosition('d18'),
    data: { label: 'feedback execuție' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd19',
    position: getNodePosition('d19'),
    data: { label: 'studiu geotehnic' },
    className: 'proiectare-flow extern w-[191px]',
  },
  {
    id: 'd20',
    position: getNodePosition('d20'),
    data: { label: 'ridicare topografică' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd21',
    position: getNodePosition('d21'),
    data: { label: 'studiu hidrologic' },
    className: 'proiectare-flow extern w-[191px]',
  },
  {
    id: 'd22',
    position: getNodePosition('d22'),
    data: { label: 'temă soluții arhitecturale și echipamente' },
    className: 'proiectare-flow extern w-[170px]',
  },
  {
    id: 'd23',
    position: getNodePosition('d23'),
    data: { label: 'poziții + înălțimi macarale' },
    className: 'proiectare-flow extern w-[175px]',
  },
  {
    id: 'd24',
    position: getNodePosition('d24'),
    data: { label: 'studii consultanți avizare' },
    className: 'proiectare-flow extern w-[175px]',
  },
  {
    id: 'd25',
    position: getNodePosition('d25'),
    data: { label: 'temă cerințe OS' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd26',
    position: getNodePosition('d26'),
    data: { label: 'poziții + proiect fundații macarale' },
    className: 'proiectare-flow extern w-[170px]',
  },
  {
    id: 'd27',
    position: getNodePosition('d27'),
    data: { label: 'temă uși tehnice și ALA în infra' },
    className: 'proiectare-flow extern w-[170px]',
  },
  {
    id: 'd28',
    position: getNodePosition('d28'),
    data: { label: 'detalii tehnice piese înglobate' },
    className: 'proiectare-flow extern w-[170px]',
  },
  {
    id: 'd29',
    position: getNodePosition('d29'),
    data: { label: 'structură buget' },
    className: 'proiectare-flow extern',
  },
  {
    id: 'd30',
    position: getNodePosition('d30'),
    data: { label: 'feedback execuție' },
    className: 'proiectare-flow extern',
  },

  {
    id: 'i1',
    position: getNodePosition('i1'),
    data: { label: 'analiză instalații teren' },
    className: 'proiectare-flow green w-[190px]',
  },
  {
    id: 'i2',
    position: getNodePosition('i2'),
    data: { label: 'temă spații tehnice și conformare' },
    className: 'proiectare-flow green w-[295px]',
  },

  {
    id: 'i1',
    position: getNodePosition('i1'),
    data: { label: 'analiză instalații teren' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i2',
    position: getNodePosition('i2'),
    data: { label: 'temă spații tehnice și conformare' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i3',
    position: getNodePosition('i3'),
    data: { label: 'concept instalații spații comune și echipamente' },
    className: 'proiectare-flow green w-[220px]',
  },
  {
    id: 'i4',
    position: getNodePosition('i4'),
    data: { label: 'concept instalații apartamente' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i5',
    position: getNodePosition('i5'),
    data: { label: 'temă auditor energetic' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i6',
    position: getNodePosition('i6'),
    data: { label: 'date pentru memorii tehnice' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i7',
    position: getNodePosition('i7'),
    data: { label: 'planuri nivel SI și PC' },
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i8',
    position: getNodePosition('i8'),
    data: { label: 'planuri instalații fundații' },
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i9',
    position: getNodePosition('i9'),
    data: { label: 'documentație DTAC' },
    className: 'proiectare-flow green w-[232px]',
  },
  {
    id: 'i10',
    position: getNodePosition('i10'),
    data: { label: 'planuri instalații infra' },
    className: 'proiectare-flow green w-36',
  },
  {
    id: 'i11',
    position: getNodePosition('i11'),
    data: { label: 'planuri supra + calcule' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i12',
    position: getNodePosition('i12'),
    data: { label: 'planuri PT infra + liste cantități + piese scrise' },
    className: 'proiectare-flow green w-[220px]',
  },
  {
    id: 'i13',
    position: getNodePosition('i13'),
    data: { label: 'planuri PT supra + liste cantități + piese scrise' },
    className: 'proiectare-flow green w-[220px]',
  },
  {
    id: 'i14',
    position: getNodePosition('i14'),
    data: { label: 'temă finală planuri goliri infra' },
    className: 'proiectare-flow green',
  },
  {
    id: 'i15',
    position: getNodePosition('i15'),
    data: { label: 'planuri elemente înglobate în beton' },
    className: 'proiectare-flow green w-[180px]',
  },
  {
    id: 'i16',
    position: getNodePosition('i16'),
    data: { label: 'PT actualizat cu echipamente selectate' },
    className: 'proiectare-flow green w-[210px]',
  },
  {
    id: 'i17',
    position: getNodePosition('i17'),
    data: { label: 'fișe tehnice apartamente' },
    className: 'proiectare-flow green w-[229px]',
  },
  {
    id: 'i18',
    position: getNodePosition('i18'),
    data: { label: 'documentație AS-BUILT' },
    className: 'proiectare-flow green w-[229px]',
  },
  {
    id: 'i19',
    position: getNodePosition('i19'),
    data: { label: 'documentație ASI' },
    className: 'proiectare-flow green w-[229px]',
  },

  {
    id: 'a1',
    position: getNodePosition('a1'),
    data: { label: 'analiză teren' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a2',
    position: getNodePosition('a2'),
    data: { label: 'documentație certificat de urbanism' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a3',
    position: getNodePosition('a3'),
    data: { label: 'concept preliminar' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a4',
    position: getNodePosition('a4'),
    data: { label: 'concept detaliat preliminar' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a5',
    position: getNodePosition('a5'),
    data: { label: 'concept final detaliat' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a6',
    position: getNodePosition('a6'),
    data: { label: 'concept validat' },
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a7',
    position: getNodePosition('a7'),
    data: { label: 'temă auditor energetic' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a8',
    position: getNodePosition('a8'),
    data: { label: 'documentații avize simple' },
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a9',
    position: getNodePosition('a9'),
    data: { label: 'documentații avize: DSP, Mediu, STS, AACR, etc.' },
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a10',
    position: getNodePosition('a10'),
    data: { label: 'documentații avize SI și PC' },
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a11',
    position: getNodePosition('a11'),
    data: { label: 'documentație circulație' },
    className: 'proiectare-flow primary w-[235px]',
  },
  {
    id: 'a12',
    position: getNodePosition('a12'),
    data: { label: 'documentație DTAC + DTOE' },
    className: 'proiectare-flow primary',
  },

  {
    id: 'a12.1',
    position: getNodePosition('a12.1'),
    data: { label: 'concept fațadă revizuit' },
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.2',
    position: getNodePosition('a12.2'),
    data: { label: 'planuri nivel preliminare' },
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.3',
    position: getNodePosition('a12.3'),
    data: { label: 'planuri nivel finale' },
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a12.4',
    position: getNodePosition('a12.4'),
    data: { label: 'documentație DTAC actualizată' },
    className: 'proiectare-flow primary w-[277px]',
  },
  {
    id: 'a13',
    position: getNodePosition('a13'),
    data: { label: 'fișă de proiect' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a14.1',
    position: getNodePosition('a14.1'),
    data: { label: 'temă arhitectură PT pentru instalații' },
    className: 'proiectare-flow primary w-[188px]',
  },
  {
    id: 'a14.2',
    position: getNodePosition('a14.2'),
    data: { label: 'temă arhitectură PT pentru structură' },
    className: 'proiectare-flow primary w-[188px]',
  },
  {
    id: 'a15',
    position: getNodePosition('a15'),
    data: { label: 'planuri coordonatoare' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a16',
    position: getNodePosition('a16'),
    data: { label: 'planuri coordonatoare goluri' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a17',
    position: getNodePosition('a17'),
    data: { label: 'planuri pentru vânzări' },
    className: 'proiectare-flow primary',
  },
  {
    id: 'a18',
    position: getNodePosition('a18'),
    data: { label: 'planuri PT pentru execuție' },
    className: 'proiectare-flow primary w-[242px]',
  },
  {
    id: 'a19',
    position: getNodePosition('a19'),
    data: { label: 'liste de cantități' },
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a20',
    position: getNodePosition('a20'),
    data: { label: 'detalii de execuție' },
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a21',
    position: getNodePosition('a21'),
    data: { label: 'piese scrise' },
    className: 'proiectare-flow primary w-[170px]',
  },
  {
    id: 'a22',
    position: getNodePosition('a22'),
    data: { label: 'planuri revizuite (feedback execuție)' },
    className: 'proiectare-flow primary w-[240px]',
  },
  {
    id: 'a23',
    position: getNodePosition('a23'),
    data: { label: 'planuri AS-BUILT' },
    className: 'proiectare-flow primary w-[170px]',
  },

  {
    id: 's1',
    position: getNodePosition('s1'),
    data: { label: 'analiză geometrică structură' },
    className: 'proiectare-flow orange',
  },
  {
    id: 's2',
    position: getNodePosition('s2'),
    data: { label: 'concept structură' },
    className: 'proiectare-flow orange',
  },
  {
    id: 's3',
    position: getNodePosition('s3'),
    data: { label: 'planuri cofraj propuse' },
    className: 'proiectare-flow orange',
  },
  {
    id: 's4',
    position: getNodePosition('s4'),
    data: { label: 'expertize' },
    className: 'proiectare-flow orange',
  },
  {
    id: 's5',
    position: getNodePosition('s5'),
    data: { label: 'planuri cofraj DTAC' },
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's6',
    position: getNodePosition('s6'),
    data: { label: 'planuri excavație + incintă' },
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's7',
    position: getNodePosition('s7'),
    data: { label: 'liste cantități preliminare' },
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's8',
    position: getNodePosition('s8'),
    data: { label: 'calcul armare elemente verticale' },
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's9',
    position: getNodePosition('s9'),
    data: { label: 'planuri armare elemente verticale' },
    className: 'proiectare-flow orange w-[300px]',
  },
  {
    id: 's10',
    position: getNodePosition('s10'),
    data: { label: 'planuri cofraj PT' },
    className: 'proiectare-flow orange',
  },
  {
    id: 's11',
    position: getNodePosition('s11'),
    data: { label: 'planuri armare grinzi + plăci supra' },
    className: 'proiectare-flow orange w-[180px]',
  },
  {
    id: 's12',
    position: getNodePosition('s12'),
    data: { label: 'planuri borduri goluri + detalii' },
    className: 'proiectare-flow orange w-[180px]',
  },
  {
    id: 's13',
    position: getNodePosition('s13'),
    data: { label: 'planuri armare grinzi, plăci și rampe infra' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's14',
    position: getNodePosition('s14'),
    data: { label: 'planuri cofraj și armare fundații' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's15',
    position: getNodePosition('s15'),
    data: { label: 'planuri cofraj și armare spații comune' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's16',
    position: getNodePosition('s16'),
    data: { label: 'planuri cofraj și armare scări duplex' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's17',
    position: getNodePosition('s17'),
    data: { label: 'planuri armare elemente speciale din beton' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's18',
    position: getNodePosition('s18'),
    data: { label: 'plan poziționare elemente din beton în zone' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's19',
    position: getNodePosition('s19'),
    data: { label: 'plan structuri metalice secundare' },
    className: 'proiectare-flow orange w-[235px]',
  },
  {
    id: 's20',
    position: getNodePosition('s20'),
    data: { label: 'liste de cantități' },
    className: 'proiectare-flow orange w-[185px]',
  },
  {
    id: 's21',
    position: getNodePosition('s21'),
    data: { label: 'piese scrise' },
    className: 'proiectare-flow orange w-[185px]',
  },
  {
    id: 's22',
    position: getNodePosition('s22'),
    data: { label: 'dispoziție de șantier' },
    className: 'proiectare-flow orange w-[185px]',
  },
];
function getMiniNodes() {
  return [
    {
      id: '6',
      label: 'Concept Arhitectural',
      link: '/flow/concept-arhitectural',
      position: { x: 10, y: 70 },
      cssClass: 'mini-flow primary w-52',
      permission,
      showIndex: true,
    },
    {
      id: '7',
      label: 'Proiectarea DTAC',
      link: null,
      position: { x: 240, y: 70 },
      cssClass: 'mini-flow primary w-40',
      permission,
      showIndex: true,
    },
    {
      id: '8',
      label: 'Autorizarea',
      link: null,
      position: { x: 424, y: 70 },
      cssClass: 'mini-flow primary w-40',
      permission,
      showIndex: true,
    },
    {
      id: 'c',
      label: 'Finanțare bancă',
      link: null,
      position: { x: 345, y: 10 },
      cssClass: 'mini-flow green w-40',
      permission,
      showIndex: true,
    },
  ];
}

/* ---------- edges ------------------------------------------------- */
function getMiniEdges() {
  return [
    {
      id: '6-7',
      source: '6',
      target: '7',
      sourceHandle: 'right',
      targetHandle: 'left',
      type: 'straight',
      style: { stroke: '#000' },
      markerEnd: { type: 'arrowclosed', color: '#000' },
      permission,
      showIndex: true,
    },
    {
      id: '7-8',
      source: '7',
      target: '8',
      sourceHandle: 'right',
      targetHandle: 'left',
      type: 'straight',
      style: { stroke: '#000' },
      markerEnd: { type: 'arrowclosed', color: '#000' },
      permission,
      showIndex: true,
    },
    {
      id: '7-c',
      source: '7',
      target: 'c',
      sourceHandle: 'top',
      targetHandle: 'left',
      type: 'step',
      style: { stroke: '#000' },
      markerEnd: { type: 'arrowclosed', color: '#000' },
      permission,
      showIndex: true,
    },
  ];
}

module.exports = {
  getNodes,
  getEdges,
  getMiniEdges,
  getMiniNodes,
  permission: '3',
  overlay: 'horizontal',
};
