/* resources/flows/prima-flow/flow-data.js
   ---------------------------------------------------------
   JSON-ready data for the landing page “PRIMA Flow”.        */

const defaultCss = 'flow primary w-[138.4px]';
const greenCss = 'flow green';
const violetCss = 'flow violet';
const yellowCss = 'flow yellow';
const pinkCss = 'flow pink';
const widePrimary = 'flow primary w-[280px]';

/* ---- NODES ---------------------------------------------------------- */
const getNodes = () => [
  /* main line ------------------------------------------------------- */
  {
    id: 'achizitie',
    label: 'Achiziția Terenului',
    link: '/flow/achizitie-teren',
    position: { x: 0, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['bottom'],
  },
  {
    id: 'concept',
    label: 'Conceptul Arhitectural',
    link: '/flow/concept-arhitectural',
    position: { x: 163.01, y: 65 },
    cssClass: defaultCss,
    targetHandles: ['bottom'],
  },
  {
    id: '3',
    label: 'Proiectarea DTAC',
    link: '/flow/proiectare',
    position: { x: 326.05, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['top'],
  },
  {
    id: 'autorizarea',
    label: 'Autorizarea',
    link: null,
    position: { x: 489.08, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['bottom'],
  },
  {
    id: 'ptdde',
    label: 'Proiectarea PT+DDE',
    link: '/flow/proiectare',
    position: { x: 652.1, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['top'],
  },
  {
    id: 'constructia',
    label: 'Construcția',
    link: null,
    position: { x: 815.12, y: 65 },
    cssClass: defaultCss,
  },
  {
    id: 'receptie',
    label: 'Recepția cu autoritățile',
    link: '/flow/intabulare',
    position: { x: 978.14, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['top', 'bottom'],
    targetHandles: ['custom-bottom'],
  },
  {
    id: '8',
    label: 'Recepția cu clienții',
    link: '/flow/receptie-clienti',
    position: { x: 1141.15, y: 65 },
    cssClass: defaultCss,
    sourceHandles: ['bottom'],
  },
  {
    id: 'remedieri',
    label: 'Remedierile în garanție',
    link: '/flow/remedieri-garantie',
    position: { x: 1304.3, y: 65 },
    cssClass: `${greenCss} w-[138.4px]`,
    targetHandles: ['bottom'],
  },

  /* secondary rows -------------------------------------------------- */
  {
    id: 'urbanisticaa',
    label: 'Autorizarea Urbanistică',
    link: null,
    position: { x: 70, y: 170 },
    cssClass: `${greenCss} w-36`,
  },
  {
    id: 'finantare',
    label: 'Finanțare bancă',
    link: null,
    position: { x: 417, y: 0 },
    cssClass: `${greenCss} w-44 h-11`,
  },
  {
    id: 'c',
    label: 'Autorizarea SSI și AP. CIV',
    link: null,
    position: { x: 1070, y: 0 },
    cssClass: `${greenCss} w-56 h-11`,
  },
  {
    id: 'utilitati',
    label: 'Branșamente la utilități',
    link: null,
    position: { x: 580, y: 140 },
    cssClass: `${pinkCss}  w-44`,
  },
  {
    id: 'setup',
    label: 'Setarea procesului de vânzări',
    link: null,
    position: { x: 580, y: 215 },
    cssClass: `${violetCss} w-44`,
  },
  {
    id: 'vanzari',
    label: 'Gestionarea vânzărilor',
    link: null,
    position: { x: 770, y: 215 },
    cssClass: `${violetCss} w-32`,
    sourceHandles: ['bottom'],
  },
  {
    id: 'pregatire-cvc',
    label: 'Pregătirea semnării CVC',
    link: null,
    position: { x: 914, y: 215 },
    cssClass: `${violetCss} w-44`,
    sourceHandles: ['bottom'],
  },
  {
    id: 'setupmrk',
    label: 'Setup-ul Marketingului',
    link: null,
    position: { x: 580, y: 290 },
    cssClass: `${yellowCss} w-44`,
    sourceHandles: ['bottom'],
  },
  {
    id: 'mrk',
    label: 'Gestionarea Marketingului',
    link: null,
    position: { x: 690, y: 365 },
    cssClass: `${yellowCss} w-40`,
  },
  {
    id: 'customer',
    label: 'Interacțiunea cu clientul',
    link: null,
    position: { x: 690, y: 440 },
    cssClass: `${yellowCss} w-40`,
  },
  {
    id: 'cvc',
    label: 'Semnarea contractelor CVC',
    link: null,
    position: { x: 1134.8, y: 215 },
    cssClass: `${defaultCss.replace('w-[138.4px]', 'w-44')}`,
    sourceHandles: ['bottom'],
    targetHandles: ['left', 'top', 'custom-left'],
  },
  {
    id: 'intabulare',
    label: 'Intabularea Apartamentelor',
    link: '/flow/intabulare',
    position: { x: 1034, y: 140 },
    cssClass: `${defaultCss.replace('w-[138.4px]', 'w-36')}`,
    sourceHandles: ['bottom'],
  },
  {
    id: 'comunicare',
    label: 'Comunicare cu clienții',
    link: null,
    position: { x: 850, y: 290 },
    cssClass: `${violetCss} w-40`,
  },
  {
    id: 'asociatie',
    label: 'Înființarea Asociației',
    link: null,
    position: { x: 1082.8, y: 365 },
    cssClass: widePrimary,
    sourceHandles: ['bottom'],
    targetHandles: ['top'],
  },
  {
    id: 'predare',
    label: 'Predarea clădirii către clienți',
    link: null,
    position: { x: 1135, y: 440 },
    cssClass: `${defaultCss.replace('w-[138.4px]', 'w-44')}`,
    targetHandles: ['top'],
  },
  {
    id: 'reautorizare',
    label: 'Reautorizarea în execuție',
    link: '/flow/proiectare-pt-dde',
    position: { x: 745, y: 0 },
    cssClass: `${greenCss} w-40`,
  },
];

/* ---- EDGES ---------------------------------------------------------- */
const getEdges = () => [
  /* ── Main line ──────────────────────────────────────────────────── */
  {
    id: 'achizitie-concept',
    source: 'achizitie',
    target: 'concept',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'concept-3',
    source: 'concept',
    target: '3',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '3-autorizarea',
    source: '3',
    target: 'autorizarea',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'autorizarea-ptdde',
    source: 'autorizarea',
    target: 'ptdde',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'ptdde-constructia',
    source: 'ptdde',
    target: 'constructia',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'constructia-receptie',
    source: 'constructia',
    target: 'receptie',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'receptie-8',
    source: 'receptie',
    target: '8',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },

  /* ── End‑cap ────────────────────────────────────────────────────── */
  {
    id: '8-remedieri',
    source: '8',
    target: 'remedieri',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  },

  /* ── Secondary links ────────────────────────────────────────────── */
  {
    id: 'achizitie-urbanisticaa',
    source: 'achizitie',
    target: 'urbanisticaa',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
    sourceHandleCss: 'left-11',              // ⬅ offset from JSX
  },
  {
    id: 'urbanisticaa-concept',
    source: 'urbanisticaa',
    target: 'concept',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'step',
    targetHandleCss: 'left-[73px]',          // ⬅ offset from JSX
  },
  {
    id: '3-finantare',
    source: '3',
    target: 'finantare',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'ptdde-reautorizare',
    source: 'ptdde',
    target: 'reautorizare',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'autorizarea-utilitati',
    source: 'autorizarea',
    target: 'utilitati',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'utilitati-receptie',
    source: 'utilitati',
    target: 'receptie',
    sourceHandle: 'right',
    targetHandle: 'custom-bottom',
    type: 'step',
    targetHandleCss: 'left-3',               // ⬅ offset from JSX
  },
  {
    id: 'autorizarea-setup',
    source: 'autorizarea',
    target: 'setup',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setup-vanzari',
    source: 'setup',
    target: 'vanzari',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'vanzari-pregatire-cvc',
    source: 'vanzari',
    target: 'pregatire-cvc',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'autorizarea-setupmrk',
    source: 'autorizarea',
    target: 'setupmrk',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setupmrk-mrk',
    source: 'setupmrk',
    target: 'mrk',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setupmrk-customer',
    source: 'setupmrk',
    target: 'customer',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'receptie-c',
    source: 'receptie',
    target: 'c',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'receptie-intabulare',
    source: 'receptie',
    target: 'intabulare',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
    sourceHandleCss: 'left-8',               // ⬅ offset from JSX
  },
  {
    id: 'intabulare-cvc',
    source: 'intabulare',
    target: 'cvc',
    sourceHandle: 'bottom',
    targetHandle: 'custom-left',
    type: 'step',
    targetHandleCss: 'top-2',                // ⬅ offset from JSX
  },
  {
    id: 'vanzari-comunicare',
    source: 'vanzari',
    target: 'comunicare',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'pregatire-cvc-cvc',
    source: 'pregatire-cvc',
    target: 'cvc',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: '8-cvc',
    source: '8',
    target: 'cvc',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
    sourceHandleCss: 'left-20',              // ⬅ offset from JSX
  },
  {
    id: 'cvc-asociatie',
    source: 'cvc',
    target: 'asociatie',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  },
  {
    id: 'asociatie-predare',
    source: 'asociatie',
    target: 'predare',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: 'predare-remedieri',
    source: 'predare',
    target: 'remedieri',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'step',
    targetHandleCss: 'left-24',              // from legacy JSX
  },
];

/* -------------------------------------------------------------------- */
module.exports = { getNodes, getEdges };
