// resources/flows/prima-flow/raw-data.js
// --------------------------------------
// Plain data only.  Two named exports:
//
//   • nodes – every node with label, link, position, cssClass
//   • edges – every edge with source/target/handles/type
//
// You may add extra fields (permission, color, etc.) later without
// touching the client builder.

const getNodes = () => [
  {
    id: 'achizitie',
    label: 'Achiziția Terenului',
    link: '/flow/achizitie-teren',
    position: { x: 0, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['bottom'],
    targetHandles: [],
  },
  {
    id: 'concept',
    label: 'Conceptul Arhitectural',
    link: '/flow/concept-arhitectural',
    position: { x: 163.01, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: [],
    targetHandles: ['bottom'],
  },
  {
    id: '3',
    label: 'Proiectarea DTAC',
    link: '/flow/proiectare-dtac',
    position: { x: 326.05, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['top'],
    targetHandles: [],
  },
  {
    id: 'autorizarea',
    label: 'Autorizarea',
    link: null,
    position: { x: 489.08, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['bottom'],
    targetHandles: [],
  },
  {
    id: 'ptdde',
    label: 'Proiectarea PT+DDE',
    link: '/flow/proiectare-pt-dde',
    position: { x: 652.1, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['top'],
    targetHandles: [],
  },
  {
    id: 'reautorizare',
    label: 'Reautorizarea în timpul execuției',
    link: '/flow/proiectare-pt-dde',
    position: { x: 745, y: 0 },
    cssClass: 'flow green w-40',
    sourceHandles: [],
    targetHandles: [],
  },
  {
    id: 'constructia',
    label: 'Construcția',
    link: null,
    position: { x: 815.12, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: [],
    targetHandles: [],
  },
  {
    id: 'receptie',
    label: 'Recepția cu autoritățile',
    link: '/flow/intabulare',
    position: { x: 978.14, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['top', 'bottom'],
    targetHandles: ['custom-bottom'],
  },
  {
    id: '8',
    label: 'Recepția cu clienții',
    link: '/flow/receptie-clienti',
    position: { x: 1141.15, y: 65 },
    cssClass: 'flow primary w-[138.4px]',
    sourceHandles: ['bottom'],
    targetHandles: [],
  },
  {
    id: 'remedieri',
    label: 'Remedierile în garanție',
    link: '/flow/remedieri-garantie',
    position: { x: 1304.3, y: 65 },
    cssClass: 'flow green w-[138.4px]',
    sourceHandles: [],
    targetHandles: ['bottom'],
  },

  // ----- secondary rows ------------------------------------------------
  {
    id: 'urbanisticaa',
    label: 'Autorizarea Urbanistică',
    link: null,
    position: { x: 70, y: 140 },
    cssClass: 'flow green w-36',
  },
  {
    id: 'finantare',
    label: 'Finanțare bancă',
    link: null,
    position: { x: 417, y: 0 },
    cssClass: 'flow green w-44 h-11',
  },
  {
    id: 'c',
    label: 'Autorizarea SSI și AP. CIV',
    link: null,
    position: { x: 1070, y: 0 },
    cssClass: 'flow green w-56 h-11',
  },
  {
    id: 'utilitati',
    label: 'BRANȘAMENTE LA UTILITĂȚI',
    link: null,
    position: { x: 580, y: 140 },
    cssClass: 'flow pink w-40',
  },

  {
    id: 'setup',
    label: 'Setarea procesului de vânzări',
    link: null,
    position: { x: 580, y: 215 },
    cssClass: 'flow violet w-40',
  },
  {
    id: 'vanzari',
    label: 'Gestionarea vânzărilor',
    link: null,
    position: { x: 763, y: 215 },
    cssClass: 'flow violet w-32',
    sourceHandles: ['bottom'],
  },
  {
    id: 'pregatire-cvc',
    label: 'Pregătirea semnării contractelor CVC',
    link: null,
    position: { x: 914, y: 215 },
    cssClass: 'flow violet w-44',
    sourceHandles: ['bottom'],
  },

  {
    id: 'setupmrk',
    label: 'Setup-ul Marketingului',
    link: null,
    position: { x: 580, y: 290 },
    cssClass: 'flow yellow w-40',
    sourceHandles: ['bottom'],
  },
  {
    id: 'mrk',
    label: 'Gestionarea Marketingului',
    link: null,
    position: { x: 690, y: 365 },
    cssClass: 'flow yellow w-40',
  },
  {
    id: 'customer',
    label: 'Interacțiunea cu clientul',
    link: null,
    position: { x: 690, y: 440 },
    cssClass: 'flow yellow w-40',
  },

  {
    id: 'cvc',
    label: 'Semnarea contractelor CVC',
    link: null,
    position: { x: 1134.8, y: 215 },
    cssClass: 'flow primary w-44',
    sourceHandles: ['bottom'],
    targetHandles: ['left', 'top', 'custom-left'],
  },
  {
    id: 'intabulare',
    label: 'Intabularea Apartamentelor',
    link: '/flow/intabulare',
    position: { x: 1034, y: 140 },
    cssClass: 'flow primary w-36',
    sourceHandles: ['bottom'],
  },
  {
    id: 'comunicare',
    label: 'Comunicare cu clienții',
    link: null,
    position: { x: 850, y: 290 },
    cssClass: 'flow violet w-40',
  },

  {
    id: 'asociatie',
    label: 'Înființarea Asociației de Proprietari',
    link: null,
    position: { x: 1082.8, y: 365 },
    cssClass: 'flow primary w-[280px]',
    sourceHandles: ['bottom'],
    targetHandles: ['top'],
  },
  {
    id: 'predare',
    label: 'Predarea clădirii către clienți',
    link: null,
    position: { x: 1135, y: 440 },
    cssClass: 'flow primary w-44',
    targetHandles: ['top'],
  },
];

const getEdges = () => [
  // main line
  {
    id: 'achizitie-concept',
    source: 'achizitie',
    target: 'concept',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'concept-3',
    source: 'concept',
    target: '3',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '3-autorizarea',
    source: '3',
    target: 'autorizarea',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'autorizarea-ptdde',
    source: 'autorizarea',
    target: 'ptdde',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'ptdde-constructia',
    source: 'ptdde',
    target: 'constructia',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'constructia-receptie',
    source: 'constructia',
    target: 'receptie',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: 'receptie-8',
    source: 'receptie',
    target: '8',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '8-remedieri',
    source: '8',
    target: 'remedieri',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  },

  // secondary connections
  {
    id: 'achizitie-urbanisticaa',
    source: 'achizitie',
    target: 'urbanisticaa',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'ptdde-reautorizare',
    source: 'ptdde',
    target: 'reautorizare',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'reautorizare-constructie',
    source: 'reautorizare',
    target: 'constructia',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'step',
  },
  {
    id: 'urbanisticaa-concept',
    source: 'urbanisticaa',
    target: 'concept',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'step',
  },
  {
    id: '3-finantare',
    source: '3',
    target: 'finantare',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },

  {
    id: 'autorizarea-utilitati',
    source: 'autorizarea',
    target: 'utilitati',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'utilitati-7',
    source: 'utilitati',
    target: 'receptie',
    sourceHandle: 'right',
    targetHandle: 'custom-bottom',
    type: 'step',
  },

  {
    id: 'autorizarea-setup',
    source: 'autorizarea',
    target: 'setup',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setup-vanzari',
    source: 'setup',
    target: 'vanzari',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'vanzari-pregatire-cvc',
    source: 'vanzari',
    target: 'pregatire-cvc',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },

  {
    id: 'autorizarea-setupmrk',
    source: 'autorizarea',
    target: 'setupmrk',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setupmrk-mrk',
    source: 'setupmrk',
    target: 'mrk',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'setupmrk-customer',
    source: 'setupmrk',
    target: 'customer',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },

  {
    id: '7-c',
    source: 'receptie',
    target: 'c',
    sourceHandle: 'top',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: '7-intabulare',
    source: 'receptie',
    target: 'intabulare',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'intabulare-cvc',
    source: 'intabulare',
    target: 'cvc',
    sourceHandle: 'bottom',
    targetHandle: 'custom-left',
    type: 'step',
  },

  {
    id: 'vanzari-comunicare',
    source: 'vanzari',
    target: 'comunicare',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: 'pregatire-cvc-cvc',
    source: 'pregatire-cvc',
    target: 'cvc',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'step',
  },
  {
    id: '8-cvc',
    source: '8',
    target: 'cvc',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  },

  {
    id: 'cvc-asociatie',
    source: 'cvc',
    target: 'asociatie',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  },
  {
    id: 'asociatie-predare',
    source: 'asociatie',
    target: 'predare',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: 'predare-remedieri',
    source: 'predare',
    target: 'remedieri',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'step',
  },
];
module.exports = { getNodes, getEdges };
