/* Plain data – safe to load on the server, no React imports */

const permission = 'intabulare'; // who may read this flow

const getNodes = () => [
  {
    id: '1',
    label: 'Anunțare finalizare lucrări',
    link: null,
    position: { x: 247, y: 25 },
    cssClass: 'receptie-flow',
  },
  {
    id: '2',
    label: 'Regularizare taxe + Obținere adeverință ISC',
    link: null,
    position: { x: 185, y: 80 },
    cssClass: 'receptie-flow',
  },
  {
    id: '3',
    label: 'Convocare comisie recepție',
    link: null,
    position: { x: 249, y: 135 },
    cssClass: 'receptie-flow',
  },
  {
    id: '4',
    label: 'Pregătire șantier',
    link: null,
    position: { x: 640, y: 25 },
    cssClass: 'receptie-flow',
  },
  {
    id: '5',
    label: 'Pregătire documentație',
    link: null,
    position: { x: 875, y: 25 },
    cssClass: 'receptie-flow',
  },
  {
    id: '6',
    label: 'Recepție cu autoritățile',
    link: null,
    position: { x: 614, y: 200 },
    cssClass: 'receptie-flow',
  },
  {
    id: '7',
    label: 'Obținere CAECC',
    link: null,
    position: { x: 195, y: 265 },
    cssClass: 'receptie-flow',
  },
  {
    id: '8',
    label: 'Înregistrare clădire la DITL',
    link: null,
    position: { x: 360, y: 330 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '9',
    label: 'Obținere acord bancă',
    link: null,
    position: { x: 623, y: 330 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '10',
    label: 'Verificare documentație cadastrală',
    link: null,
    position: { x: 845, y: 330 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '11',
    label: 'Intabularea clădirii',
    link: null,
    position: { x: 510, y: 395 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '12',
    label: 'Actualizare cadastru - construcție',
    link: null,
    position: { x: 185, y: 460 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '13',
    label: 'Întocmire poliță de asigurare',
    link: null,
    position: { x: 735, y: 460 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '14',
    label: 'Dezmembrare locuri de parcare',
    link: null,
    position: { x: 456.7, y: 515 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '15',
    label: 'Obținere acord bancă',
    link: null,
    position: { x: 775, y: 515 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '16',
    label: 'Radiere sarcini',
    link: null,
    position: { x: 1005, y: 515 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '17',
    label: 'Dezmembrare teren la OCPI',
    link: null,
    position: { x: 956.7, y: 570 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '18',
    label: 'Dezmembrare prin act-adițional',
    link: null,
    position: { x: 625, y: 635 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '19',
    label: 'Înscriere act dezmembrare la DIT',
    link: null,
    position: { x: 932.4, y: 635 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '20',
    label: 'Obținere certificat lot clădire',
    link: null,
    position: { x: 940.5, y: 690 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '21',
    label: 'Apartamentare clădire',
    link: null,
    position: { x: 491.4, y: 745 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '22',
    label: 'Obținere acord bancă',
    link: null,
    position: { x: 741, y: 745 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '23',
    label: 'Propunere apartamentare la OCPI',
    link: null,
    position: { x: 970, y: 745 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '24',
    label: 'Semnare acte notariale + Obținere intabulare',
    link: null,
    position: { x: 920.6, y: 800 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '25',
    label: 'Înregistrare la DITL',
    link: null,
    position: { x: 1026.2, y: 855 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '26',
    label: 'Obținere acord bancă înstrăinare',
    link: null,
    position: { x: 676, y: 855 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '27',
    label: 'Obținere certificate finale individuale',
    link: null,
    position: { x: 226, y: 855 },
    cssClass: 'intabulare-flow',
  },
  {
    id: '28',
    label: 'Vânzare apartamente',
    link: null,
    position: { x: 503, y: 920 },
    cssClass: 'intabulare-flow',
  },
];

const getEdges = () => [
  {
    id: '1-2',
    source: '1',
    target: '2',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '2-3',
    source: '2',
    target: '3',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '3-6',
    source: '3',
    target: '6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'short-step',
  },
  {
    id: '4-6',
    source: '4',
    target: '6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '5-6',
    source: '5',
    target: '6',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'short-step',
  },
  {
    id: '6-7',
    source: '6',
    target: '7',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '7-11',
    source: '7',
    target: '11',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '8-11',
    source: '8',
    target: '11',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '9-11',
    source: '9',
    target: '11',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '10-11',
    source: '10',
    target: '11',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '11-12',
    source: '11',
    target: '12',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '11-13',
    source: '11',
    target: '13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '11-14',
    source: '11',
    target: '14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '14-15',
    source: '14',
    target: '15',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '15-16',
    source: '15',
    target: '16',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '16-17',
    source: '16',
    target: '17',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '17-18',
    source: '17',
    target: '18',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '17-19',
    source: '17',
    target: '19',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '19-20',
    source: '19',
    target: '20',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '18-21',
    source: '18',
    target: '21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'step',
  },
  {
    id: '20-21',
    source: '20',
    target: '21',
    sourceHandle: 'left',
    targetHandle: 'top',
    type: 'step',
  },

  {
    id: '21-22',
    source: '21',
    target: '22',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },
  {
    id: '22-23',
    source: '22',
    target: '23',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'straight',
  },

  {
    id: '23-24',
    source: '23',
    target: '24',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '24-25',
    source: '24',
    target: '25',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '25-28',
    source: '25',
    target: '28',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '26-28',
    source: '26',
    target: '28',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '27-28',
    source: '27',
    target: '28',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },

  {
    id: '14-21',
    source: '14',
    target: '21',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
  {
    id: '21-28',
    source: '21',
    target: '28',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'straight',
  },
];
module.exports = { getNodes, getEdges, permission };
